environment: beta
project_name: JEWEL
report_name: JEWEL-UI
jewel_user: dipanshu.geco
jewel_bridge_token: 73d0c859-f0c6-4e4f-ab71-9f351282c6991704108093947
enter_point: https://apis.gemecosystem.com/gemEcosystemDashboard/v1/enter-point
tags: ''
scenario: ''
feature: src/main/resources/features
console_report: n
jewel_screen_shots: y
event_firing: n
glue_code: StepDefination
auto_kill: y
prod:
  browser_name: CHROME_HEADLESS
  launch_url: https://jewel.gemecosystem.com/
  browser_timeout: 10
beta:
  browser_name: CHROME_HEADLESS
  launch_url: https://jewel-beta.gemecosystem.com/
  browser_timeout: 10
